### Requisição para criar um novo paciente
POST http://localhost:8000/api/pacientes/ HTTP/1.1
Content-Type: application/json

{
  "paciente": {
    "nome": "João da Silva",
    "pseudonimo": "Joãozinho",
    "data_nascimento": "1985-05-15",
    "genero": [15, 16],
    "orientacao_sexual": [36, 35],
    "religiao": [5, 6, 7],
    "alergias": [109, 108],
    "ja_fez_psicoterapia": true,
    "ja_fez_psiquiatrico": false,
    "ja_fez_tratamento_espirita": true
  }
}

### Criação de um novo paciente com dados aninhados
POST http://localhost:8000/api/pacientes/ HTTP/1.1
Content-Type: application/json

{
  "paciente": {
    "nome": "João da Silva",
    "pseudonimo": "Joãozinho",
    "data_nascimento": "1985-05-15",
    "genero": [15, 16],
    "orientacao_sexual": [36, 35],
    "religiao": [5, 6, 7],
    "alergias": [109, 108],
    "ja_fez_psicoterapia": true,
    "ja_fez_psiquiatrico": false,
    "ja_fez_tratamento_espirita": true
  },
  "enderecos": 
    {
      "cep": "12345678",
      "estado": "São Paulo",
      "cidade": "São Paulo",
      "bairro": "Centro",
      "tipo_logradouro": "RUA",
      "logradouro": "Av. Paulista",
      "numero": "1000",
      "complemento": "Apto 101"
    }
  ,
  "telefones": [
    {
      "rotulo": "Celular",
      "ddd": "11",
      "telefone": "987654321",
      "whatsapp": true,
      "telegram": false,
      "ligacao": true
    },
    {
      "rotulo": "Residencial",
      "ddd": "11",
      "telefone": "34567890",
      "whatsapp": false,
      "telegram": false,
      "ligacao": true
    }
  ],
  "emails": [
    {
      "email": "joao.silva@example.com"
    },
    {
      "email": "joaozinho@example.com"
    }
  ]
}



### TODO selectvalue novo está enable, deveria ser tocheck
### Criar novo select
POST http://localhost:8000/api/selectvalues/ HTTP/1.1
Content-Type: application/json

{
    "select_type": "RELIG",
    "value": "Catolifganoiw",
    "state": "ENA"
}



### Requisição GET para a SelectValueView
GET http://localhost:8000/api/selectvalues/?select_type=RELIG&search_term=catoli HTTP/1.1
Accept: application/json


